### PR TITLE
API changes

### PR DESCRIPTION
**Pull request by ghost**
Sync with http://git.infradead.org/users/jjs/linux-isgx.git ioctl API.

### CODE REVIEW

**Comment by andyzyb** [comment]
The SGX SDK/PSW is not ready for the change of driver APIs, so please hold on the pull request.

**Comment by ghost** [comment]
Ok, please merge this when you can.

**Comment by andyzyb** [comment]
How about creating a branch and merging all the changes to it, so we can continue testing and update that branch while master branch is still working with linux-sgx repo?

**Comment by jsakkine-intel** [comment]
I dropped all the patches that are not mandatory for integrating 1.5 changes.

**Pull request merged**
